name: build

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: cdupuis
          password: ${{ secrets.HUB_PAT }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cdupuis/frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
     