name: build

on:
  push:
    branches:
      - main

  merge_group:
  pull_request:
    branches:
      - main

jobs:

  changed-files:
    runs-on: ubuntu-latest
    name: setup-build

    permissions:
      pull-requests: read
      contents: read

    outputs:
      matrix: ${{ steps.build-files.outputs.DHI_CHANGED_FILES }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get all changed files
        id: changed-files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            all:
              added|modified: 
                - 'image/**/*'
                - 'package/**/*'
          list-files: json

     